### ISSUE TITLE
ValueError: invalid literal for int() with base 10 in opensubtitles.py

### ISSUE THREAD

**Issue by infernix** [pannal/Sub-Zero.bundle#105]
Seeing this:

```
2015-12-28 18:49:16,290 (7f6ae3fff700) :  DEBUG (logger:28) - guessit.guess: Updating matching property 'container' with confidence 1.00
2015-12-28 18:49:16,291 (7f6ae3fff700) :  DEBUG (logger:28) - guessit.matchtree: Final result: {
    [1.00] "mimetype": "video/x-matroska", 
    [0.60] "episodeNumber": 8, 
    [1.00] "container": "mkv", 
    [0.30] "title": "Twenty-five Little Pre-pubers", 
    [0.42] "series": "Two and a Half Men", 
    [1.00] "type": "episode", 
    [0.60] "season": 1
}
2015-12-28 18:49:16,291 (7f6ae3fff700) :  INFO (logger:38) - subliminal_patch.patch_subtitle: Computing score for matches set([u'episode', u'series', u'year'
, u'season', u'hearing_impaired']) and <Episode [u'Two and a Half Men', 1x8]>
2015-12-28 18:49:16,292 (7f6ae3fff700) :  DEBUG (logger:28) - subliminal_patch.patch_subtitle: Final matches: set([u'series', u'episode', u'hearing_impaired'
, u'season', u'year'])
2015-12-28 18:49:16,292 (7f6ae3fff700) :  INFO (logger:38) - subliminal_patch.patch_subtitle: Computed score 111
2015-12-28 18:49:16,292 (7f6ae3fff700) :  INFO (logger:38) - subliminal_patch.patch_provider_pool: Downloading subtitle <OpenSubtitlesSubtitle 'http://www.op
ensubtitles.org/en/subtitles/5997469/sid-ecftqe0melcvj8gqf0o29b1st0/two-and-a-half-men-twenty-five-little-pre-pubers-without-a-snoot-ful-nl' [nl]> with score
 115
2015-12-28 18:49:16,292 (7f6ae3fff700) :  INFO (logger:38) - subliminal_patch.patch_provider_pool: Downloading subtitle <OpenSubtitlesSubtitle 'http://www.op
ensubtitles.org/en/subtitles/5997469/sid-ecftqe0melcvj8gqf0o29b1st0/two-and-a-half-men-twenty-five-little-pre-pubers-without-a-snoot-ful-nl' [nl]>
2015-12-28 18:49:16,293 (7f6ae3fff700) :  INFO (logger:38) - subliminal.providers.opensubtitles: Downloading subtitle <OpenSubtitlesSubtitle 'http://www.open
subtitles.org/en/subtitles/5997469/sid-ecftqe0melcvj8gqf0o29b1st0/two-and-a-half-men-twenty-five-little-pre-pubers-without-a-snoot-ful-nl' [nl]>
2015-12-28 18:49:16,346 (7f6ae3fff700) :  ERROR (logger:36) - subliminal_patch.patch_provider_pool: Unexpected error in provider u'opensubtitles', Traceback: Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_provider_pool.py", line 214, in download_subtitle
    self[subtitle.provider_name].download_subtitle(subtitle)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/providers/opensubtitles.py", line 185, in download_subtitle
    response = checked(self.server.DownloadSubtitles(self.token, [str(subtitle.subtitle_id)]))
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/providers/opensubtitles.py", line 237, in checked
    status_code = int(response['status'][:3])
ValueError: invalid literal for int() with base 10: ''
2015-12-28 18:49:16,347 (7f6ae3fff700) :  ERROR (logger:36) - subliminal_patch.patch_provider_pool: Maximum retries reached for provider u'opensubtitles', discarding it
2015-12-28 18:49:16,347 (7f6ae3fff700) :  INFO (logger:38) - subliminal_patch.patch_provider_pool: Downloading subtitle <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/4382068/sid-ecftqe0melcvj8gqf0o29b1st0/two-and-a-half-men-twenty-five-little-pre-pubers-without-a-snoot-ful-nl' [nl]> with score 111
2015-12-28 18:49:16,348 (7f6ae3fff700) :  WARNING (logger:36) - subliminal_patch.patch_provider_pool: Provider u'opensubtitles' is discarded
2015-12-28 18:49:16,348 (7f6ae3fff700) :  INFO (logger:38) - subliminal_patch.patch_provider_pool: Downloading subtitle <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/6128451/sid-ecftqe0melcvj8gqf0o29b1st0/two-and-a-half-men-twenty-five-little-pre-pubers-without-a-snoot-ful-nl' [nl]> with score 111
```

Are you checking the opensubtitles response for ```407 Download limit reached```? I'm unsure what kind of status is actually being returned that results in this error, but could be related to the daily cap.

**Comment by infernix** [comment]
Interestingly, I logged in at Opensubtitles.org and solved a captcha and the error went away.

**Comment by pannal** [comment]
They most likely throttled you in some way. It's not SZ-related.

**Comment by infernix** [comment]
And you don't think there should be a better way of handling the error than to just fail?

Are you honoring the daily download limit at all?

**Comment by pannal** [comment]
It's not really failing, it just prints the traceback for more info than just skipping the provider.
I could handle the non-existant return code, though. Though that's more likely something which should be fixed in subliminal.

And no, as the errors are not clear, OpenSubtitles will just be skipped for that run and tried again later.

**Comment by infernix** [comment]
I'm guessing the captcha I filled was just coincidental, errors came back a minute or two after. So I had a look, turned off https to the api and fired up wireshark

```
2015-12-28 19:41:19,606 (7f37567fc700) :  DEBUG (logger:28) - subliminal.providers.opensubtitles: response: {'status': '', 'seconds': 0.003, 'data': ''}
```

Client logs in (1/5):
```xml
<?xml version='1.0'?>
<methodCall>
<methodName>LogIn</methodName>
<params>
<param>
<value><string></string></value>
</param>
<param>
<value><string></string></value>
</param>
<param>
<value><string>eng</string></value>
</param>
<param>
<value><string>subliminal v1.0</string></value>
</param>
</params>
</methodCall>
```
Server responds 200 OK:
```xml
<?xml version="1.0" encoding="utf-8"?>
<methodResponse>
<params>
 <param>
  <value>
   <struct>
    <member>
     <name>token</name>
     <value>
      <string>93itf1366uslb5sfmum3n2iq27</string>
     </value>
    </member>
    <member>
     <name>status</name>
     <value>
      <string>200 OK</string>
     </value>
    </member>
    <member>
     <name>seconds</name>
     <value>
      <double>0.002</double>
     </value>
    </member>
   </struct>
  </value>
 </param>
</params>
</methodResponse>
```

Client searches (2/5):
```xml
<?xml version='1.0'?>
<methodCall>
<methodName>SearchSubtitles</methodName>
<params>
<param>
<value><string>93itf1366uslb5sfmum3n2iq27</string></value>
</param>
<param>
<value><array><data>
<value><struct>
<member>
<name>moviebytesize</name>
<value><string>1510615486</string></value>
</member>
<member>
<name>sublanguageid</name>
<value><string>dut,rus</string></value>
</member>
<member>
<name>moviehash</name>
<value><string>74de8b3e1daaf548</string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>query</name>
<value><string>Utopia</string></value>
</member>
<member>
<name>sublanguageid</name>
<value><string>dut,rus</string></value>
</member>
<member>
<name>episode</name>
<value><int>5</int></value>
</member>
<member>
<name>season</name>
<value><int>2</int></value>
</member>
</struct></value>
</data></array></value>
</param>
</params>
</methodCall>
```
Server responds 200 OK:
```xml
<?xml version="1.0" encoding="utf-8"?>
<methodResponse>
<params>
 <param>
  <value>
   <struct>
    <member>
     <name>status</name>
     <value>
      <string>200 OK</string>
     </value>
    </member>
    <member>
     <name>data</name>
     <value>
      <array>
       <data>
        <value>
         <struct>
          <member>
           <name>MatchedBy</name>
           <value>
            <string>fulltext</string>
           </value>
          </member>
          <member>
           <name>IDSubMovieFile</name>
           <value>
            <string>0</string>
           </value>
          </member>
          <member>
           <name>MovieHash</name>
           <value>
            <string>0</string>
           </value>
          </member>
          <member>
           <name>MovieByteSize</name>
           <value>
            <string>0</string>
           </value>
          </member>
          <member>
           <name>MovieTimeMS</name>
           <value>
            <string>0</string>
           </value>
          </member>
          <member>
           <name>IDSubtitleFile</name>
           <value>
            <string>1954579463</string>
           </value>
          </member>
          <member>
           <name>SubFileName</name>
           <value>
            <string>Utopia.2x05.720p_HDTV_x264.srt</string>
           </value>
          </member>
          <member>
           <name>SubActualCD</name>
           <value>
            <string>1</string>
           </value>
          </member>
          <member>
           <name>SubSize</name>
           <value>
            <string>59164</string>
           </value>
          </member>
          <member>
           <name>SubHash</name>
           <value>
            <string>811b4e6f93e8ac3d59be08696b3f05c7</string>
           </value>
          </member>
          <member>
           <name>SubLastTS</name>
           <value>
            <string>00:48:11</string>
           </value>
          </member>
          <member>
           <name>IDSubtitle</name>
           <value>
            <string>6000221</string>
           </value>
          </member>
          <member>
           <name>UserID</name>
           <value>
            <string>1805995</string>
           </value>
          </member>
          <member>
           <name>SubLanguageID</name>
           <value>
            <string>rus</string>
           </value>
          </member>
          <member>
           <name>SubFormat</name>
           <value>
            <string>srt</string>
           </value>
          </member>
          <member>
           <name>SubSumCD</name>
           <value>
            <string>1</string>
           </value>
          </member>
          <member>
           <name>SubAuthorComment</name>
           <value>
            <string/>
           </value>
          </member>
          <member>
           <name>SubAddDate</name>
           <value>
            <string>2015-01-12 15:08:15</string>
           </value>
          </member>
          <member>
           <name>SubBad</name>
           <value>
            <string>0</string>
           </value>
          </member>
          <member>
           <name>SubRating</name>
           <value>
            <string>0.0</string>
           </value>
          </member>
          <member>
           <name>SubDownloadsCnt</name>
           <value>
            <string>78</string>
           </value>
          </member>
          <member>
           <name>MovieReleaseName</name>
           <value>
            <string> Utopia.2x05.720p_HDTV_x264</string>
           </value>
          </member>
          <member>
           <name>MovieFPS</name>
           <value>
            <string>25.000</string>
           </value>
          </member>
          <member>
           <name>IDMovie</name>
           <value>
            <string>180533</string>
           </value>
          </member>
          <member>
           <name>IDMovieImdb</name>
           <value>
            <string>3902654</string>
           </value>
          </member>
          <member>
           <name>MovieName</name>
           <value>
            <string>&#34;Utopia&#34; Episode #2.5</string>
           </value>
          </member>
          <member>
           <name>MovieNameEng</name>
           <value>
            <string/>
           </value>
          </member>
          <member>
           <name>MovieYear</name>
           <value>
            <string>2014</string>
           </value>
          </member>
          <member>
           <name>MovieImdbRating</name>
           <value>
            <string>9.0</string>
           </value>
          </member>
          <member>
           <name>SubFeatured</name>
           <value>
            <string>0</string>
           </value>
          </member>
          <member>
           <name>UserNickName</name>
           <value>
            <string>gdx</string>
           </value>
          </member>
          <member>
           <name>ISO639</name>
           <value>
            <string>ru</string>
           </value>
          </member>
          <member>
           <name>LanguageName</name>
           <value>
            <string>Russian</string>
           </value>
          </member>
          <member>
           <name>SubComments</name>
           <value>
            <string>0</string>
           </value>
          </member>
          <member>
           <name>SubHearingImpaired</name>
           <value>
            <string>0</string>
           </value>
          </member>
          <member>
           <name>UserRank</name>
           <value>
            <string>bronze member</string>
           </value>
          </member>
          <member>
           <name>SeriesSeason</name>
           <value>
            <string>2</string>
           </value>
          </member>
          <member>
           <name>SeriesEpisode</name>
           <value>
            <string>5</string>
           </value>
          </member>
          <member>
           <name>MovieKind</name>
           <value>
            <string>episode</string>
           </value>
          </member>
          <member>
           <name>SubHD</name>
           <value>
            <string>1</string>
           </value>
          </member>
          <member>
           <name>SeriesIMDBParent</name>
           <value>
            <string>2384811</string>
           </value>
          </member>
          <member>
           <name>SubEncoding</name>
           <value>
            <string>UTF-8</string>
           </value>
          </member>
          <member>
           <name>QueryParameters</name>
           <value>
            <struct>
             <member>
              <name>query</name>
              <value>
               <string>utopia</string>
              </value>
             </member>
             <member>
              <name>episode</name>
              <value>
               <string>5</string>
              </value>
             </member>
             <member>
              <name>season</name>
              <value>
               <string>2</string>
              </value>
             </member>
             <member>
              <name>sublanguageid</name>
              <value>
               <string>rus</string>
              </value>
             </member>
            </struct>
           </value>
          </member>
          <member>
           <name>SubDownloadLink</name>
           <value>
            <string>http://dl.opensubtitles.org/en/download/file/src-api/vrf-19e20c5e/sid-93itf1366uslb5sfmum3n2iq27/1954579463.gz</string>
           </value>
          </member>
          <member>
           <name>ZipDownloadLink</name>
           <value>
            <string>http://dl.opensubtitles.org/en/download/sub/src-api/vrf-f4fe0ba4/sid-93itf1366uslb5sfmum3n2iq27/6000221</string>
           </value>
          </member>
          <member>
           <name>SubtitlesLink</name>
           <value>
            <string>http://www.opensubtitles.org/en/subtitles/6000221/sid-93itf1366uslb5sfmum3n2iq27/utopia-episode-2-5-ru</string>
           </value>
          </member>
          <member>
           <name>QueryNumber</name>
           <value>
            <int>3</int>
           </value>
          </member>
         </struct>
        </value>
       </data>
      </array>
     </value>
    </member>
    <member>
     <name>seconds</name>
     <value>
      <double>0.015</double>
     </value>
    </member>
   </struct>
  </value>
 </param>
</params>
</methodResponse>
```

Client requests download (3/5):
```xml
<?xml version='1.0'?>
<methodCall>
<methodName>DownloadSubtitles</methodName>
<params>
<param>
<value><string>93itf1366uslb5sfmum3n2iq27</string></value>
</param>
<param>
<value><array><data>
<value><string>1954579463</string></value>
</data></array></value>
</param>
</params>
</methodCall>
```

Problem occurs here where  server responds with 200 OK but no content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<methodResponse>
<params>
 <param>
  <value>
   <struct>
    <member>
     <name>status</name>
     <value>
      <string/>
     </value>
    </member>
    <member>
     <name>data</name>
     <value>
      <string/>
     </value>
    </member>
    <member>
     <name>seconds</name>
     <value>
      <double>0.01</double>
     </value>
    </member>
   </struct>
  </value>
 </param>
</params>
</methodResponse>
```

Then client logs out (4/5):
```xml
<?xml version='1.0'?>
<methodCall>
<methodName>LogOut</methodName>
<params>
<param>
<value><string>93itf1366uslb5sfmum3n2iq27</string></value>
</param>
</params>
</methodCall>
```
Server 200 OKs:
```xml
<?xml version="1.0" encoding="utf-8"?>
<methodResponse>
<params>
 <param>
  <value>
   <struct>
    <member>
     <name>status</name>
     <value>
      <string>200 OK</string>
     </value>
    </member>
    <member>
     <name>seconds</name>
     <value>
      <double>0.002</double>
     </value>
    </member>
   </struct>
  </value>
 </param>
</params>
</methodResponse>
```

And finally this seems entirely redundant, client sends 'close' (5/5):
```xml
<?xml version='1.0'?>
<methodCall>
<methodName>close</methodName>
<params>
</params>
</methodCall>
```
Server 200 OKs:
```xml
<?xml version="1.0" encoding="utf-8"?>
<methodResponse>
<params>
 <param>
  <value>
   <struct>
    <member>
     <name>status</name>
     <value>
      <string>409 Method not found</string>
     </value>
    </member>
    <member>
     <name>seconds</name>
     <value>
      <double>0.001</double>
     </value>
    </member>
   </struct>
  </value>
 </param>
</params>
</methodResponse>
```


Very weird, since no error or status is returned and HTTP status is a 200.

If it's a server issue, it could be useful to alter ```def download_subtitle``` to retry X times with Y delay whenever the status field is empty. I'll give that a try and see if that resolves the issue. [Subliminal seems to raise an error](https://github.com/bramwalet/Subliminal.bundle/blob/master/Contents/Libraries/Shared/subliminal/providers/opensubtitles.py#L144) whenever ```response['data']``` is empty, which may be better if it turns out it's never going to return any data.

**Comment by infernix** [comment]
It seems to have resolved itself after entering my (non-VIP) opensubtitles.org credentials. I'll keep an eye out if it reoccurs while logged in with an actual account, if not it is probably some form of badly implemented throttling which causes an invalid XMLRPC response.

**Comment by pannal** [comment]
Thanks for testing, please report back :)

**Comment by infernix** [comment]
After using credentials I'm only getting  ```DownloadLimitReached``` so I'd say it's safe to assume that this is occurring only when not logged in.

I'd suggest to add to the documentation that it's strongly recommended to use an account with opensubtitles.org.
