### ISSUE TITLE
Downloaded subtitles are showed twice in Plex GUI

### ISSUE THREAD

**Issue by eleonrk** [pannal/Sub-Zero.bundle#215]
I'm not sure if it's started since the last SZ update or few days before that, but currently each time I have a new episode or a new movie added to my Plex library, SZ downloads the subtitle and each subtitle is showed twice in the Plex GUI, although in my file system, there is only one file for the subtitle :
![1](https://cloud.githubusercontent.com/assets/2619959/20983006/2770d456-bcbb-11e6-982a-24deaddecf26.PNG)

Here is my configuration : http://imgur.com/a/kYufb

When I delete the subtitle from the file system, only one raw is delete in Plex GUI and when selected, the second one makes my Plex crash when I start watching the episode (or the movie).

I'm not sure where this is coming from.

**Comment by pannal** [comment]
Yes it did. It has been already reported in the forums and is fixed in the current develop-1.4 branch.

The next release will fix that.

**Comment by guyspronck** [comment]
@pannal this issue still exists for me on the current release (Sub-Zero 1.4.27.973). Anything I can do to fix this?
This is what it looks like:
![image](https://cloud.githubusercontent.com/assets/8409187/25420698/a04757ea-2a59-11e7-9ac0-9ba1dd382914.png)

**Comment by pannal** [comment]
Could you tell me your subtitle settings in SZ? Do you save in subfolder or besides the media file?

Can you screenshot me a media folder where this happens? I have a hunch.

**Comment by guyspronck** [comment]
@pannal I just messed a bit with my settings to figure out what the issue is. I was saving the .srt files next to the media files, I disabled it and removed the srt files from my media folder. After refreshing the metadata, only the one sub persisted which worked.

Also, I should note: from the screenshot I sent, the second subtitle would not load and would block playing of my media.

To wrap up, disabling `Store subtitles next to media files (instead of metadata)` and removing the .srt files fixed the issue for me.

**Comment by pannal** [comment]
Ok, this is a serious issue, though. We need to fix this, as it's a core feature. 

I guessed that you stored the subtitles externally, but where exactly? "current folder"? 

I need more information about your system. I bet you're using Windows? 

Please provide the screenshot I've requested in my last reply.

**Comment by guyspronck** [comment]
Plex is running on my QNAP TS-251, which also hosts the media files. I chose to save the .srt files next to the media files using "current folder".
This is my current configuration: (without saving the srt file)
![image](https://cloud.githubusercontent.com/assets/8409187/25431174/caea5b48-2a7f-11e7-8015-ff0568b0dfcc.png)
![image](https://cloud.githubusercontent.com/assets/8409187/25431189/d91ecd2a-2a7f-11e7-9b3a-f9f9d45f0e29.png)
![image](https://cloud.githubusercontent.com/assets/8409187/25431202/e380ed16-2a7f-11e7-8575-7f590b3da274.png)
![image](https://cloud.githubusercontent.com/assets/8409187/25431210/ecf1a246-2a7f-11e7-8372-cfd4f890e93b.png)

**Comment by pannal** [comment]
OK, I'll run some tests and get back to you. Thank you for reporting the issue (again)!

**Comment by guyspronck** [comment]
If you want me to test anything or any specific settings, let me know! My guess is that Sub-Zero sets the sub in the metadata and saves the srt. But because of the srt being there, plex discovers it as a 'new' subtitle, making it appear twice.

**Comment by pannal** [comment]
Nope, that's most likely not the case. I think Plex's local media agent itself picks up the subtitle, and SZs own local media implementation adds it as well (using a slightly different path, hence the duplicate).

Can you test setting the storage location to the "subs" folder? The issue should go away.

**Comment by guyspronck** [comment]
Just did that and it indeed resolves the issue for me, it now created the subs folder and put the subtitles in there without appearing twice in plex. This does work for me, as I still have the .srt file (sometimes I just want to put the movie on a USB drive), and now does now show duplicated.

**Comment by pannal** [comment]
Yep, that confirms the issue. I'll have to fix that behaviour, though as "current folder" is the default setting :)

**Comment by pannal** [comment]
That's so weird. I can't reproduce this. Can you show me the order of agents in that particular library?

**Comment by guyspronck** [comment]
It's set as the first option for agents in both movies and TV.

I'll update this reply in about an hour with a directory listing, but it's just linux in the end. It happens to every movie/TV show, so is not related to any special characters.

**Comment by pannal** [comment]
Then something is very different from your setup to mine. I still can't reproduce that behaviour, mine don't get duplicated.

**Comment by guyspronck** [comment]
```
[/share/Multimedia/Movies/Alien (1979)] # ls -al
total 6877844
drwxr-xr-x    4 admin    administ      4096 Apr 26 13:25 ./
drwxrwxrwx   65 admin    administ      4096 Apr 21 07:21 ../
drwxrwxrwx    3 admin    administ      4096 Apr 26 08:27 .@__thumb/
-rw-r--r--    1 admin    administ 7042886698 Dec  2  2003 Alien.mkv
drwxr-xr-x    2 admin    administ      4096 Apr 26 13:25 subs/
```
This is what a directory looks like with the file names etc.

**Comment by pannal** [comment]
I'll have to get you a debug build ready I think. Can you disable the plex local media agent and try if that still happens?

**Comment by guyspronck** [comment]
I just disabled and disabled the plex local media agent, then the issue does not happen if the sub is in the same directory.

```
[/share/Multimedia/Movies/Alien (1979)] # ls -al
total 6877884
drwxr-xr-x    3 admin    administ      4096 Apr 26 17:45 ./
drwxrwxrwx   65 admin    administ      4096 Apr 21 07:21 ../
drwxrwxrwx    3 admin    administ      4096 Apr 26 08:27 .@__thumb/
-rw-r--r--    1 admin    administ 7042886698 Dec  2  2003 Alien.mkv
-rw-r--r--    1 admin    administ     42775 Apr 26 17:45 Alien.nl.srt
```
![image](https://cloud.githubusercontent.com/assets/8409187/25443503/53b23964-2aa8-11e7-89d4-59777c8bbdf5.png)

**Comment by pannal** [comment]
And Local Media Assets is below Sub-Zero yes? No other subtitle agent enabled?

**Comment by guyspronck** [comment]
You are correct.

**Comment by pannal** [comment]
OK. Here's what you can do - I need to see what data is stored in the PMS database about your item(s).

Please do the following:
- re-trigger the duplicate bug
- go to an item in plexweb where there's duplicate external subs
- click on the `...`, `Get Info`
- click on `View XML`
- note the `id="..."` part of `<Media videoResolution="720" id="..." ...>`
- create a copy of `Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db`
- open the copy of that database with a SQLite viewer (I'm using [this one](https://github.com/sqlitebrowser/sqlitebrowser/releases))
- go to the table `media_streams` and filter for the ID you just noted, in the `media_item_id` field
- post the content of the `url` field of each row, where `stream_type_id` = 3

I know it's a lot to ask, but I can't debug it any other way.

Thank you!

**Comment by guyspronck** [comment]
Yup, there we go! I've followed your steps and I now see what the issue is.
So here are the paths for the .srt files, the top one is the one created by SubZero, the bottom one by Plex.:
`file:///share/CACHEDEV1_DATA/Multimedia/Movies/Alien (1979)/Alien.nl.srt`
`file:///share/Multimedia/Movies/Alien (1979)/Alien.nl.srt`

So what you see here is two paths pointing to the same file with different directories. So what the issue here is, the way QNAPs are setup: the 'real' directory/share location is `/share/CACHEDEV1_DATA/<share_name>` but because that does not look great it is symlinked to `/share/<share_name>` which you can see in the above paths. I configured Plex to use the better looking directory, whilst it appears that subzero uses the personal working directory from the fs, thus ending up with two different paths to the same file.

So this issue is caused by having a symlink to a movie folder and using the symlink in plex. My guess is that you can reproduce this issue by creating a movie folder, symlinking it to somewhere, using the symlink in plex and then running SubZero over it.

Hope this helps! These kind of edge-cases are always hard to track down

**Comment by pannal** [comment]
Yeah. I also know when that bug was introduced.

I'm using os.path.realpath on the file locations since the end of 2016, which also translates symlinks.

Pushing a fix, would you care to try it out?

**Comment by pannal** [comment]
You can try following [this guide](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation) and install [this branch](https://github.com/pannal/Sub-Zero.bundle/archive/develop-1.4.zip).

**Comment by guyspronck** [comment]
I will do this over the weekend, will report back with my findings.

**Comment by pannal** [comment]
Thank you. The installation is quite forward and takes only a minute if you're used to the procecure.

**Comment by pannal** [comment]
I'm fairly certain this issue has been fixed; I've fast-tracked a separate release (1.4.27.974) into the queue.

**Comment by guyspronck** [comment]
I can confirm the issue is resolved in version 1.4.27.974!

**Comment by pannal** [comment]
Great, thank you for reporting in!

**Comment by Nottt** [comment]
This is still happening to me on Sub-Zero 2.0.26.1715

**Comment by ggbalcal** [comment]
This bug still exists.

Plex Server 1.10.1.4602 
Sub-Zero 2.0.33.1871

Tow srt in xml. The first one crashes the transcoding. 

Workaround:
option 1: disable "Local Media Assets" agent, or
option 2: select none subtitle or the 2nd subtitle

**Comment by ggbalcal** [comment]
BTW, the video file is not a symlink or in a symlink directory. 

Also the video used to be in a different folder. I moved it in a new folder and rescaned the library. Not sure whether this matters.

**Comment by pannal** [comment]
@ggbalcal it may be related to that. Did you notice this for all of your media files?

**Comment by ggbalcal** [comment]
yes, all media files that were moved.

**Comment by ggbalcal** [comment]
@pannal, I did the steps you mentioned above to look into DB. I see there are two srt as expected. The first one points to the place before I moved the media directory. The 2nd one points to the right directory. Therefore, when rendering happens, it picks the first one and failed. So my question is why it still has the old path and how I can remove them in all the media files I moved.

**Comment by pannal** [comment]
I think WebTools can do that for you. Am I right @ukdtom ?

**Comment by ukdtom** [comment]
Yes and no....
If on Mac, then sadly currently disabled, due to our beloved framework acts differently on Mac vs. other platforms.

If not on Mac, then maybe, but a tad unsure here, if the srt file is missing...., but think it would work...

Sad thing regardless is though, that it's a manual process one by one for each sub, so a faster approach might be the Plex Dance

**Comment by ukdtom** [comment]
https://github.com/ukdtom/WebTools.bundle/wiki/Subs

**Comment by ggbalcal** [comment]
@ukdtom, Is "Scan Library File" the same as "Update Library" in the Plex Dance?

Unfortunately, the server is on Mac.

**Comment by ggbalcal** [comment]
Tried Plex Dance. It didn't work. It still has the outdated sub in every media.

**Comment by ggbalcal** [comment]
@ukdtom, thanks. The Plex Dance fixed the problem. But strangely, It didn't remove the outdated sub path. Rather, it somehow replaced it with the sidecar subtitle.

**Comment by ukdtom** [comment]
That I can't tell...

But glad you found a work around though
