### ISSUE TITLE
Sub-Zero not seeing my TV shows folder

### ISSUE THREAD

**Issue by JDFS404** [pannal/Sub-Zero.bundle#258]
Hi,

Sub-Zero is magnificent regarding my Movies, but if I go to _Channels > Sub-Zero Subtitles > Browse all items_ I don't see my TV shows folder popping up...

Could you help me? I already deleted the TV shows out of Plex, refreshed it but to no avail.

**Comment by pannal** [comment]
Is the agent enabled for your TV shows? Please have a look [here](https://github.com/pannal/Sub-Zero.bundle/wiki/Agent-configuration).

**Comment by JDFS404** [comment]
Yes, it is. I have followed all your instructions, even set the score to 77 :(.

**Comment by pannal** [comment]
OK. Then I'll need logs. Please [see the wiki again](https://github.com/pannal/Sub-Zero.bundle/wiki/Support#logging) on how to do so - also: attach them here or upload them somewhere. Please don't paste them.

**Comment by JDFS404** [comment]
Okay, it's making progress. Now, it's seeing the folder:

![schermafbeelding 2017-03-27 om 09 39 35](https://cloud.githubusercontent.com/assets/26678110/24345680/7f6be5f8-12d1-11e7-8395-d28c59519b1b.png)

However, still not downloading...I will upload my log as soon as I'm possible to get it (have to SSH into my NAS).

**Comment by JDFS404** [comment]
Here is the log! http://www103.zippyshare.com/v/h0JaZsDM/file.html

**Comment by pannal** [comment]
Hey, I'm seeing an awful lot of matches for files like `s01e09.mkv`. That is extremely few information for SZ to work on. 

Also, how is your series library configured? How's your file structure? I'm seeing a search for `Follow The Money` which seems like an episode name, not a series name.

**Comment by pannal** [comment]
That's still weird. The log shows many entries about files named `s02e06.mkv`, which is pretty much impossible to clean-match for SZ.

But I now see why it's happening: `IOError: [Errno 13] Permission denied: '/volume1/XXXXXX/XXXXXX/Season 3/S03E03.nl.srt'`

Please [see the permissions article in the wiki for that](https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ#sub-zero-complains-about-permissions). Also next time please zip up all of the sub zero log files, thank you :)

**Comment by JDFS404** [comment]
My permissions are good, because Sub Zero managed to give me all my subtitles for movies.

I have changed all the names of the episodes.

I'm at a loss, please see all my recent logs: http://www6.zippyshare.com/v/JUhMMzjb/file.html

**Comment by pannal** [comment]
I can see "DownloadLimitReached" for OpenSubtitles in your logs. Should resolve itself during the next few days.

**Comment by pannal** [comment]
Please reopen if it still is an issue.

**Comment by JDFS404** [comment]
Hi pannal,

Still an issue. I'm really at a loss right now... I think it has something to do with my permissions, but I can't fix it by myself.

Here are my latest logs: http://www30.zippyshare.com/v/p7Td2QuH/file.html

**Comment by pannal** [comment]
You forgot the newest log file (the one without the .X at the end).

**Comment by pannal** [comment]
I'm seeing in your old logs that SZ downloads subtitles for you. What's currently the problem?

**Comment by JDFS404** [comment]
I'm sorry @pannal, I forgot those but not now: http://www41.zippyshare.com/v/O5AMCByA/file.html.

Technically, you're right. SZ is downloading subtitles for my movies but not for my TV shows! I want SZ also to download for my TV shows. Really at a loss here...

**Comment by pannal** [comment]
From the logs I see it downloaded subtitles for The Wire, Westworld, 

But I also see permission errors: `IOError: [Errno 13] Permission denied: '/volume1/Series/Westworld/Season 1/Westworld S01E10 The Bicameral Mind.en.srt'`

Please make sure, the library folders are always fully accessible by the user the PMS runs as.

**Comment by JDFS404** [comment]
Alright, so I copied the files to a new folder and BAM SZ is downloading! It was definitely a permissions issue...

I use Sonarr to create/rename/change files of my series, and CouchPotato for my movies. I think the trouble is with Sonarr... Do you know of this issue between SZ and Sonarr? If yes, do you have a solution?

**Comment by pannal** [comment]
The trouble is not SZ related - it's your setup. I'm guessing Sonarr or your downloader runs as a different user and the permissions of the created folders aren't correct. You can either put your Plex user in the same group as the downloader-user and set the folder permissions to 775 or so. There are many ways to fix this.

You can also go to the sonarr settings and configure the permissions there. If you don't want to fiddle with groups at all, set both permissions to 777.

Having a group with the correct permissions is the better way, though.

**Comment by pannal** [comment]
@ukdtom is this a Synology NAS? You only support QNAP, right?

**Comment by ukdtom** [comment]
Correct, and suggest @JDFS404 post rights related Q's in the [Syno forum ](http://forums.plex.tv/categories/synology) on the Plex forums.

Also, @JDFS404 , please don't use zippyshare.com
Not very nice with multiple pages loaded in my browser for porn etc.

Next time, I strongly suggest either attach the zip here, or provide a less active site, like dropbox
