### ISSUE TITLE
External subtitles which don't match naming scheme are not recognized by SubZero

### ISSUE THREAD

**Issue by MeesterPro** [pannal/Sub-Zero.bundle#260]
When you have external subtitles like
```
coincidence-assassinscreed-1080p-eng.idx
coincidence-assassinscreed-1080p-eng-forced.idx
```
or 
```
encounters-unblwa_1080p_eng.idx
encounters-snowden_1080p_eng_forced.idx
```

Subzero doesn't recognize them because they don't match the naming scheme (matching naming scheme would be encounters-unblwa_1080p.en.idx), so Subzero is going to download subtitles from the web and you end up having double subtitles.

An advanced parsing mechanism is needed, to 1. detect language and 2. to detect forced subtitles.

Issue/Feature-Request is related to [forum post of panni](https://forums.plex.tv/discussion/comment/1410024/#Comment_1410024).

**Comment by pannal** [comment]
Thank you. Will be added at a certain point.

**Comment by pannal** [comment]
This should be mitigated by the new external subtitle matching strictness setting. Can you confirm=

**Comment by pannal** [comment]
Should be fixed in 1.4.27.957

**Comment by MeesterPro** [comment]
Not really.

The difference is only that non name-matching scheme subtitles are detected and submitted to Plex, but subtitles are still getting downloaded, resulting in double subtitles.

[Archiv.zip](https://github.com/pannal/Sub-Zero.bundle/files/888414/Archiv.zip)

**Comment by pannal** [comment]
Right.

**Comment by MeesterPro** [comment]
For Plex it doesn't seem to be a problem that the title (of the subtitle) doesn't contain the language in accordance to the naming scheme: It correctly displays the language of the subtitle.

![bildschirmfoto 2017-04-03 um 19 51 21](https://cloud.githubusercontent.com/assets/26827987/24622909/f5e06d64-18a6-11e7-9a26-b2065b057902.png)
