### ISSUE TITLE
SSL erros with opensubtitles

### ISSUE THREAD

**Issue by diogorolo** [pannal/Sub-Zero.bundle#421]
Hello,

I'm getting the following error while downloading some Portuguese subtitles.

   

> 2018-01-05 22:22:29,936 (41ac) :  ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 122, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 73, in __getitem__
    provider.initialize()
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 149, in initialize
    self.log_in()
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 117, in log_in
    lambda: checked(
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\mixins.py", line 38, in retry
    return f()
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 119, in <lambda>
    os.environ.get("SZ_USER_AGENT", "Sub-Zero/2"))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 897, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 859, in send
    self.connect()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 353, in wrap_socket
    _context=self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 601, in __init__
    self.do_handshake()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

It looks the same as bug #369 .

**Comment by pannal** [comment]
They've been in a maintenance period. Is this resolved now?

**Comment by diogorolo** [comment]
Hello @pannal ,

I still have the same error:
> 2018-01-06 11:51:58,236 (2948) :  ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 122, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 73, in __getitem__
    provider.initialize()
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 149, in initialize
    self.log_in()
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 117, in log_in
    lambda: checked(
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\mixins.py", line 38, in retry
    return f()
  File "C:\Users\****\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 119, in <lambda>
    os.environ.get("SZ_USER_AGENT", "Sub-Zero/2"))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 897, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 859, in send
    self.connect()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 353, in wrap_socket
    _context=self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 601, in __init__
    self.do_handshake()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by diogorolo** [comment]
I have opensubtitles as the secondary agent on plex and that plugin/agent is able to download some subtitles.

**Comment by diogorolo** [comment]
I've locally changed the default_url from https to http and it started working as expected since we no longer need ssl... https://github.com/pannal/Sub-Zero.bundle/blob/eb3a0d52fde281773ba5109fad9801ede9c938ba/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py#L75

**Comment by pannal** [comment]
Weird, for me it still works. On which SZ version are you?

**Comment by diogorolo** [comment]
Version 2.0.33.1871 which is the latest.
