### ISSUE TITLE
Embedded subtitles being ignored, new subtitles download regardless.

### ISSUE THREAD

**Issue by kjac3585** [pannal/Sub-Zero.bundle#454]
I've got an MKV that has subtitles embedded, however after checking the setting "Don't search for subtitles of a language if there are embedded subtitles inside the media file (MKV/MP4)?" and then deleting the srt file that subzero had previously downloaded, when I refresh the movie within the subzero interface it redownloads the srt file. Is this how it's supposed to work? I was thinking it should not download anything since there are already embedded subtitles (labeled as English with both forced and full subs).

I've included the screenshot from MakeMKV showing the embedded subtitles.

![capture](https://user-images.githubusercontent.com/7411003/36937345-69b87b64-1ed7-11e8-83fb-f090e920a2d9.PNG)

EDIT: I've since tried this on several other MKV's and the results are the same, forced English subtitles are downloaded by subzero even when they already exist inside the MKV file.

**Comment by pannal** [comment]
Hey, it's hard to see anything inside your logs, as the filebot refiner spews errors like crazy:
`IOError: [Errno 2] No such file or directory: u'\\\\?\\L:\\_MOVIES\\House II The Second Story (1987)\\House II The Second Story (1987).mkv:net.filebot.filename'`

Is that a network mount you're accessing there? It doesn't find any filebot attributes as it seems.

Please turn off the filebot renaming option in SZ's settings, set SZ's log level to DEBUG, refresh an episode in question, then post your logs again, thank you!

**Comment by kjac3585** [comment]
[Logs_180303_12-40-00.zip](https://github.com/pannal/Sub-Zero.bundle/files/1777768/Logs_180303_12-40-00.zip)

I cleared out the logs and restarted PMS. I did a manual refresh through subzero on 4 movies that I knew had existing full and forced subs. The first movie I refreshed did not download any extra subtitles, the next 3 movies did, however. I refreshed the first movie again and it still did not download any subtitles. Perhaps it's some kind of subtitle naming issue, but every movie had embedded subtitles that were labeled English and the forced subs were labeled with "English" and "forced".

**Comment by pannal** [comment]
You didn't change the log level for SZ to DEBUG in those logs: `Setting log-level to WARNING`, this way I can't see anything useful.

As a side note: If you rename your files, SZ will have a hard time finding subtitles for your stuff, though. If the source format (WEB-DL, BluRay etc.) and/or the release group, isn't inside the file names, it will most likely find none. That can be circumvented by connecting SZ to the renaming medium (in this case it seems like filebot, but you seem to use a network share or something that doesn't carry the filebot attributes).

**Comment by kjac3585** [comment]
[Logs_180303_13-35-32.zip](https://github.com/pannal/Sub-Zero.bundle/files/1777815/Logs_180303_13-35-32.zip)

Ok, log debugging is enabled this time, I thought you had meant for me to check those debug boxes at the bottom. 

I refreshed the same 4 movies this time, starting with 30 Days of Night (2007), Inglourious Basterds (2009), War for the Planet of the Apes (2017), and 2012 (2009). 30 Days worked as expected, no downloads were made, but the others have the same problem as before. I looked at the logs myself and I'm guessing the issue is that it sees these embedded subtitles, however, it does not recognize them as being English. I'm not sure why though because they are labeled as English inside the mkv container.

I'm not having any issues with subzero finding subtitles as all of my movies are renamed through Radarr. I had Filebot setup on there because there were a few tv series I renamed through Filebot. I'm not using any network shares, all my drives are on the same machine as Plex.

**Comment by pannal** [comment]
Ah OK, so parts of the files are renamed using Radarr and some using filebot. That explains why there are so many errors about missing filebot attributes.

For the detection of the embedded streams: there have been fixed inside the latest release. Would you care trying to [manually install](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation) the [newest version](https://github.com/pannal/Sub-Zero.bundle/releases/download/2.5.0.2287/Sub-Zero.bundle-2.5.0.2287.zip)?

**Comment by kjac3585** [comment]
I installed the newer version, but it did not fix the issue. II've attached the new log file.

[Logs_180303_14-41-42.zip](https://github.com/pannal/Sub-Zero.bundle/files/1777872/Logs_180303_14-41-42.zip)

**Comment by pannal** [comment]
OK, please install https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.1.zip instead, I've added a different language detection mechanism and debug log entries.

Also, can you attach the XML of the media file? (Go to plex web -> that media file -> three dots -> Get Info -> View XML)

**Comment by kjac3585** [comment]
[Logs_180303_15-28-50.zip](https://github.com/pannal/Sub-Zero.bundle/files/1777919/Logs_180303_15-28-50.zip)

Installed this latest version, I refreshed two movies that I had problems with last time and had the same issues on this version. The XML files are in the zip.

**Comment by pannal** [comment]
OK. It behaves correctly. Inglourious basterds only has an embedded forced SRT so it would only be detected as existing if you had the `Only download foreign/forced subtitles` flag set. It has internal PGS subtitles, which would be detected if you had `Include non-text subtitle formats (anything else than .srt/.ssa/.ass/.vtt; embedded or external) in the above?` set.

The same is true for War for the planet of the apes.

**Comment by pannal** [comment]
Would you expect SZ to detect the forced subtitles as existing ones as well, even though you didn't enable the specific option?

**Comment by kjac3585** [comment]
I was using the forced subs only setting. I've included new logs and a screenshot of my current settings. All the settings were what I have been using the entire time, except for _"Include non-text subtitle formats (anything else than .srt/.ssa/.ass/.vtt; embedded or external) in the above?"_ I just enabled that setting with the latest log. Even with that option selected I'm still getting the external srt downloads for all 3 movies. I didn't include the movie "2012" with the previous log and I should have because it uses embedded srt files instead of the PGS, however, external srts are still downloaded for it as well with these newest settings.

[Logs_180303_15-59-09.zip](https://github.com/pannal/Sub-Zero.bundle/files/1777942/Logs_180303_15-59-09.zip)
![capture](https://user-images.githubusercontent.com/7411003/36939781-bce3cc10-1efc-11e8-9f93-3adf85459799.png)

**Comment by pannal** [comment]
Interesting, I'll try to reproduce that, give me a minute.

**Comment by pannal** [comment]
Weird. I've just tried to reproduce the issue and I can't.

**Comment by kjac3585** [comment]
Hmm, not sure what else to do. I sent you a dropbox video capture link to your reddit account showing exactly what I'm doing, maybe that might help.

**Comment by pannal** [comment]
I've made a separate build for you with more debug logging: https://github.com/pannal/Sub-Zero.bundle/archive/embedded_subs_%23454.zip

Can you retry please?

**Comment by kjac3585** [comment]
[Logs_180303_21-22-19.zip](https://github.com/pannal/Sub-Zero.bundle/files/1778151/Logs_180303_21-22-19.zip)

Here you go.

**Comment by pannal** [comment]
OK, the one I've got the XML for is War for the planet of the apes, which also is coming up inside the last log file. Is there an external subtitle besides the media file?

It detects this: `Found subtitle stream: <plex.objects.library.stream.Stream object at 0x09CA9B50>; forced only: True, stream forced: True, stream key: '/library/streams/86577', stream codec: 'srt'`

Which is the same as `<Stream id="86577" key="/library/streams/86577" streamType="3" forced="1" codec="srt" language="English" languageCode="eng" format="srt" />`, which, in my book, is an external subtitle and not an embedded one. The other PGS subtitle streams aren't picked up because they aren't forced.

**Comment by kjac3585** [comment]
I ran all 4 of the movies that you have xml files for again in this newest log. There may have been an external srt file when I restarted subzero, but I deleted it before running a refresh. I can delete and refresh over and over again and it always downloads the forced srt even though an embedded one exists. The only directory I have external subs is in my _MOVIES directory and since I've been having this issue I had deleted every external sub for all movies in order to start over fresh.

[Logs_180303_22-10-22.zip](https://github.com/pannal/Sub-Zero.bundle/files/1778182/Logs_180303_22-10-22.zip)

**Comment by pannal** [comment]
Is there a `subs_11105.json.gz` file inside `/Plug-in\ Support/Data/com.plexapp.agents.subzero/DataItems/` if so, could you attach it?

**Comment by kjac3585** [comment]
[subs_11105.json.gz](https://github.com/pannal/Sub-Zero.bundle/files/1778191/subs_11105.json.gz)

I'm not able to open the file, but there it is.

**Comment by pannal** [comment]
OK, another thing, for 2012 (2009) you have those streams:
```
<Stream id="56858" streamType="2" selected="1" default="1" codec="dca" index="1" channels="6" bitrate="1536" language="English" languageCode="eng" audioChannelLayout="5.1(side)" profile="dts" samplingRate="48000" />
<Stream id="56859" streamType="3" default="1" codec="srt" index="2" language="English" languageCode="eng" title="english" />
<Stream id="56860" streamType="3" codec="srt" index="3" language="English" languageCode="eng" title="forced" />
<Stream id="85681" key="/library/streams/85681" streamType="3" forced="1" codec="srt" language="English" languageCode="eng" format="srt" />
```

The two you see in Potplayer are index 2 and index 3 - both of those are *not* forced by forced-flag. Index 3 is forced by title "forced", which is what you see in Potplayer. I can add a special case for that and check the title attribute as well. I'm guessing stream ID `85681` is an external sub, either besides the media file or inside your metadata storage.

**Comment by pannal** [comment]
I've updated https://github.com/pannal/Sub-Zero.bundle/archive/embedded_subs_%23454.zip with stream.title == "forced" = stream.forced detection. Does that help?

**Comment by pannal** [comment]
Updated it again, now it detects titles with "forced" inside them as forced subtitles.

**Comment by pannal** [comment]
Sorry, and again, with a slightly smarter stream title detection.

**Comment by kjac3585** [comment]
ok let me install this one as well. So far I want to say it looks like it is working properly with embedded srt and pgs, but when I refreshed The Hunt for Red October (with embedded full English subs only) it did not download the forced subs. I'll install this new version and try it again and upload logs.

**Comment by pannal** [comment]
Well "properly", the quotes because the creators of the MKV file didn't properly flag the subtitle stream as forced, but instead only added "forced" to the stream title for me to detect :)

**Comment by kjac3585** [comment]
Yes, "properly", although it seems like it's a pretty common mistake these release groups make because I had many more mkv's with the same issue. 

Maybe the log files will be more telling, but as far as I can see it's downloading the srt's that it should and not downloading the ones it shouldn't. 

[Logs_180303_22-59-36.zip](https://github.com/pannal/Sub-Zero.bundle/files/1778215/Logs_180303_22-59-36.zip)

**Comment by pannal** [comment]
Looks good in my book. Updated the scanning and removed the debug logs, merging into develop-2.1. This will be included in the next release.

Thank you for debugging with me!

**Comment by kjac3585** [comment]
Sure thing. You know one thing I just realized is Plex also doesn't recognize the embedded subtitles as forced when they are improperly tagged, so you have to enable them manually. I'm trying to use the embedded subtitles because they are most likely to be accurate, so I wonder if I can use your plugin to extract them from the MKV and then properly tag them as forced? I'm not sure if that's outside of the scope of your plugin.

**Comment by pannal** [comment]
I could try automatically modifying the embedded stream meta info in the PMS database if SZ detects them as forced but their flag isn't set. That might even be a tad more elegant.

**Comment by kjac3585** [comment]
Sound good to me, is that a "quick fix" or would I need to be on the look out for it in future release?

**Comment by pannal** [comment]
That quick fix is now in https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.5.zip

You can either install that or wait for the next release.

When extracting an embedded-forced subtitle, SZ now extracts it with the `.forced` attribute and it will be pushed into the Plex database as such.

The fix for the embedded stream flags may be added later on.

**Comment by kjac3585** [comment]
So I've got this version installed now and just tinkering around with it a little. Does this plugin only extract embedded subs if they are already in SRT format? I noticed nothing was being extracted on mkv's that had the PGS embedded subs. Also a little error popped up in the logs that I thought you might want to know about.

`2018-03-04 09:53:06,336 (d70c) :  ERROR (logkit:22) - Something went wrong when auto-extracting subtitles, continuing: Traceback (most recent call last):
  File "C:\Users\kjaco\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\__init__.py", line 127, in agent_extract_embedded
    embedded_subs = stored_subs.get_by_provider(part.id, requested_language, "embedded")
  File "C:\Users\kjaco\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subzero\subtitle_storage.py", line 218, in get_by_provider
    if subtitle.provider_name == provider_name:
AttributeError: 'dict' object has no attribute 'provider_name'`

[Logs_180304_09-54-31.zip](https://github.com/pannal/Sub-Zero.bundle/files/1778668/Logs_180304_09-54-31.zip)

**Comment by pannal** [comment]
It currently only supports text based embedded subtitles, yes. I'll look into the error, thank you.

**Comment by pannal** [comment]
@kjac3585 the issue should be fixed in the revision I just pushed.

**Comment by kjac3585** [comment]
Sure, I'll test it. I'm not all that familiar with the different subtitle formats, but would this be only PGS or all image-based subtitles?

Also, I've since run SZ and had it update all my movies with forced subs, either extracting the embedded SRTs or downloading the best-matched sub for any embedded PGS/image-based sub movies. Will this proposed version of SZ overwrite the downloaded/image-based subs with the newly extracted ones? I know there's a rating system in place for sub quality, I just don't know if that rating applies to extracted subs and if SZ will see an extracted sub as being preferred over a downloaded one.

**Comment by pannal** [comment]
Automatically extracted subs get assigned a score of 0 and are set as current, if there's no current subtitle set. That way they'll be superseded by any other subtitle downloaded by the find better subtitles task. They are valid subtitles, though, and are treated as such.

I don't know whether that answers your question. The problem with PGS subs is that they're image based and we'd need some sort of OCR mechanism to extract those to a usable text format. I guess that's way out of scope right now.

**Comment by pannal** [comment]
Let's move this discussion to #455
