### ISSUE TITLE
Problem Extracting subs inside movie container

### ISSUE THREAD

**Issue by ahiguero** [pannal/Sub-Zero.bundle#460]
Version Sub-Zero 2.5.0.2287 DEV

Platform : Plex server Version 1.11.3.4803 running on the nvidia shield

issue

the following error appears when the option to extract subs from MKV is enabled
2018-03-04 18:56:00,339 (2034373450) :  ERROR (menu_helpers:186) - Extraction failed: Traceback (most recent call last):
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/interface/menu_helpers.py", line 184, in extract_embedded_sub
    output = subprocess.check_output(quote_args(args), stderr=subprocess.PIPE, shell=True)
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/helpers.py", line 30, in quote_args
    return ' '.join(quote(arg) for arg in seq)
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/helpers.py", line 30, in <lambda.2>
    return ' '.join(quote(arg) for arg in seq)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/lib/python2.7/pipes.py", line 269, in quote
    for c in file:
TypeError: 'NoneType' object is not iterable
[Logs_180307_08-22-19.zip](https://github.com/pannal/Sub-Zero.bundle/files/1789458/Logs_180307_08-22-19.zip)

**Comment by pannal** [comment]
First of all, you seem to have permission issues: `IOError: [Errno 13] Permission denied: u'/storage/RIOMAR/media/movies/Blade of the Immortal (2017)/Blade of the Immortal (2017) Bluray-1080p x264 DTS.en.srt'`

For the issue you have: SZ doesn't seem to find the Plex Transcoder. Can you search for the `Plex Transcoder` file inside `/data/user/0/com.plexapp.mediaserver.smb`?

**Comment by ahiguero** [comment]
the shares are accessible (read/write for everyone) there is something
definitely weird with the permissions for the processes inside the shield

**Comment by pannal** [comment]
@ahiguero were you able to find the path to Plex Transcoder? Then I can hopefully fix the issue.

**Comment by ahiguero** [comment]
the transcoder is inside the Resources folder 

path would be com.plexapp.mediaserver.smb/Resources/Plex Transcoder

regarding the permissions the user that connects to the share folders used to host the media files do have read and write permissions as i am able to for example delete media files from plex. but for some reason the pluging has issues writing to that folder.

**Comment by pannal** [comment]
OK, the transcoder finding issue should be resolved in the next version.

For your permission problem: I have no idea. Are the folder permissions correct? Because deleting media files requires different permissions compared to creating a new file inside a folder (which depends on the folder permissions, not the file permissions).

**Comment by ahiguero** [comment]
the folder permissions are correct i have even set it up to everyone having
read write access and still happens. i am relying on the sub-zero plugin
running on the NAS to properly extract embeded subs for now.

**Comment by pannal** [comment]
Well, permission issues are out of scope for SZ, as it can't do anything about them. Closing this for now, please reopen if the Plex Transcoder issue persists after the next version.
