### ISSUE TITLE
S-Z working flawlessly for movies but it refuses to download any subtitle for any TV-show.

### ISSUE THREAD

**Issue by KBlixt** [pannal/Sub-Zero.bundle#475]
I'm on ubuntu16.04, Sub-Zero Subtitles (TV, 2.5.0.2221), plex 1.12.1.4885.

ok, so apparently SZ stopped working for some reason. although it used to work a week ago, I haven't changed anything in my library settings or plex settings in the past week except for adding sonarr to my server. 

what am I doing wrong? sending log. see below.

**Comment by KBlixt** [comment]
[com.plexapp.agents.subzero.log.tar.gz](https://github.com/pannal/Sub-Zero.bundle/files/1846167/com.plexapp.agents.subzero.log.tar.gz)

log immediately after updating metadata for 3 episodes.

**Comment by eltanque** [comment]
Same issue here, with Windows 10, SZ 2.5.3.2414, Plex  1.12.1.4885
same error msgs as above:
[SZ_LOG_EXTRACT.txt](https://github.com/pannal/Sub-Zero.bundle/files/1847845/SZ_LOG_EXTRACT.txt)

**Comment by pannal** [comment]
The ResponseNotReady stuff should be fixed in develop-2.5 and will be in the next hotfix release.

**Comment by eltanque** [comment]
I know this is closed and fixed, and my setup is working now, but the pluggin still shows version 2.5.3.2414
<img width="221" alt="capture" src="https://user-images.githubusercontent.com/25337285/38002787-fa91c5d0-327f-11e8-9b96-bb01401668f7.PNG">

**Comment by pannal** [comment]
It can take a couple of hours for your PMS to pick up the update. Completely out of my control, sorry.

**Comment by pannal** [comment]
This hasn't been fixed properly.
