### ISSUE TITLE
Subtitles stopped downloading

### ISSUE THREAD

**Issue by amrelrayess** [pannal/Sub-Zero.bundle#588]
I am new to linux and i am facing an issue with sub zero as my subtitles were downloading then they stopped, below are the logs:
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log.1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log.2
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log.3
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log.4
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log.5
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2461834/com.plexapp.agents.subzero.log)
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2461835/com.plexapp.agents.subzero.log)

**Comment by amrelrayess** [comment]
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2461846/com.plexapp.agents.subzero.log)

**Comment by amrelrayess** [comment]
i fixed the permissions and set the owner to plex:plex for all the media folders, and the unrar is in the path specified.
i uninstalled the plugin and reinstalled it again, and here is the new log
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2462018/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
In your latest log there's nothing wrong. Can you set SZ to DEBUG mode and attach your log zip after refreshing an item?

**Comment by amrelrayess** [comment]
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2484353/com.plexapp.agents.subzero.log)





here are the logs after debugging enabled

**Comment by amrelrayess** [comment]
[SZ Plugin Logs.tar.gz](https://github.com/pannal/Sub-Zero.bundle/files/2484370/SZ.Plugin.Logs.tar.gz)
 here are the full logs

**Comment by pannal** [comment]
I can see that you're throttled at OpenSubtitles from the logs. Some of that will be partly fixed with 2.6.

I can't see anything else wrong though. Can you refresh an item, then post the debug logs again?

**Comment by pannal** [comment]
OK, in addition to the OpenSubtitles issue, you need to fix your folder/file permissions:
`IOError: [Errno 13] Permission denied: u'/2TB/Sieres/Supergirl/Season 4/Supergirl.S04E02.HDTV.x264-SVA[eztv].ar.srt'`

**Comment by amrelrayess** [comment]
i have done a fresh install of ubuntu 18.04 and installed plex by the book. then i set the owner of the folder to be plex:plex then i did chmod 777 on the whole drive the installed SZ now i see different errors in the Logs attached. 
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2520770/com.plexapp.agents.subzero.log)

**Comment by amrelrayess** [comment]
i found that the SZ plugin is suddely not in the plugins tab in plex web interface, but it is available in the agents tab in settings and when i selected to install plugins it appears to be installed, i removed it and installed it again but the same issue, attached are the new logs
[com.plexapp.agents.subzero.zip](https://github.com/pannal/Sub-Zero.bundle/files/2520852/com.plexapp.agents.subzero.zip)

**Comment by pannal** [comment]
Yeah that's a bug that's fixed in 2.6. #585 #547

**Comment by amrelrayess** [comment]
what about the critical errors in the logs

**Comment by pannal** [comment]
Those should also be fixed in 2.6.

**Comment by amrelrayess** [comment]
ok thanks a million :) 
when will it 2.6 be released

**Comment by amrelrayess** [comment]
i still have the same issues attached you will find the screenshots of the permissions and the log files, i have tried uninstalling the plug-in and re installing again, i tried restarting the server, but still nothing
![selection_001](https://user-images.githubusercontent.com/19951995/48218787-5f196e80-e393-11e8-8b3d-458e81a9f768.png)
![metadata](https://user-images.githubusercontent.com/19951995/48218797-63458c00-e393-11e8-8c33-b286abc33ffb.png)
[com.plexapp.agents.subzero.zip](https://github.com/pannal/Sub-Zero.bundle/files/2562997/com.plexapp.agents.subzero.zip)

**Comment by amrelrayess** [comment]
i am on ubuntu 18.04 LTS

**Comment by pannal** [comment]
And you are on the latest SZ version?

**Comment by amrelrayess** [comment]
yes 2.6.4.2834

**Comment by pannal** [comment]
Still permission issues: `IOError: [Errno 13] Permission denied: u'/2tb/Movies/HD/The Equalizer 2 (2018) [WEBRip] [720p] [YTS.AM]/The.Equalizer.2.2018.720p.WEBRip.x264-[YTS.AM].ar.srt'`

**Comment by amrelrayess** [comment]
this is the latest log
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2564247/com.plexapp.agents.subzero.log)

**Comment by amrelrayess** [comment]
is SZ using a different user than plex?

**Comment by pannal** [comment]
I'm not sure, can you post a `ls -als "/2tb/Movies/HD/Mission Impossible - Fallout (2018) [WEBRip] [720p] [YTS.AM]/"` and `ls -als "/2tb/Movies/HD/Mission Impossible - Fallout (2018) [WEBRip] [720p] [YTS.AM]/Mission.Impossible.-.Fallout.2018.720p.WEBRip.x264-[YTS.AM].ar.srt"` ?

**Comment by amrelrayess** [comment]
ls -als "/2tb/Movies/HD/Mission Impossible - Fallout (2018) [WEBRip] [720p] [YTS.AM]/"
total 1298632
      4 drwxr-xr-x 1 amr  amr        4096 Nov  7 03:23  .
    192 drwxrwxrwx 1 plex plex     196608 Nov  7 02:13  ..
1298376 -rw-r--r-- 1 amr  amr  1329533784 Nov  7 03:23 'Mission.Impossible.-.Fallout.2018.720p.WEBRip.x264-[YTS.AM].mp4'
     60 -rw-r--r-- 1 amr  amr       58132 Nov  7 02:16  www.YTS.AM.jpg

**Comment by amrelrayess** [comment]
ls -als "/2tb/Movies/HD/Mission Impossible - Fallout (2018) [WEBRip] [720p] [YTS.AM]/Mission.Impossible.-.Fallout.2018.720p.WEBRip.x264-[YTS.AM].ar.srt"
ls: cannot access '/2tb/Movies/HD/Mission Impossible - Fallout (2018) [WEBRip] [720p] [YTS.AM]/Mission.Impossible.-.Fallout.2018.720p.WEBRip.x264-[YTS.AM].ar.srt': No such file or directory

**Comment by pannal** [comment]
Yeah, you can see: amr:amr is the owner of the folder.

**Comment by pannal** [comment]
I guess the application that downloads the files should be in the same group as plex and set 775 on everything it downloads.

Nevertheless: this is a system problem, I can't really help with that.

**Comment by amrelrayess** [comment]
what does the u' mean after permission denied?

**Comment by pannal** [comment]
Just that it's a unicode string. Nothing special in this case.

**Comment by pannal** [comment]
The folder `/2tb/Movies/HD/Mission Impossible - Fallout (2018) [WEBRip] [720p] [YTS.AM]/` is owned by amr:amr, as you can see in `4 drwxr-xr-x 1 amr amr 4096 Nov 7 03:23 .`.

You may have fixed the permissions by `chown`ing before, but the new folders are created by the wrong user and/or with the wrong permissions.

**Comment by amrelrayess** [comment]
what about the below errors?
2018-11-09 15:28:47,291 (7f6fca7fc700) :  CRITICAL (agentkit:1078) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 2.6.4.2834)', called with guid 'com.plexapp.agents.thetvdb://328724?lang=en' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 184, in update
    all_videos = media_to_videos(media, kind=self.agent_type)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/plex_media.py", line 126, in media_to_videos
    imdb_id = media.guid[len(imdb_guid_identifier):].split("?")[0]
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/items.py", line 35, in get_item
    item_container = Plex["library"].metadata(item_id)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/interfaces/library/__init__.py", line 9, in metadata
    response = self.http.get('metadata', rating_key)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/core/http.py", line 95, in get
    return self.request('GET', path, params, query, data, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/core/http.py", line 87, in request
    response = request.request.send()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/lib.py", line 33, in send
    timeout=DEFAULT_TIMEOUT)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 194, in Request
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

2018-11-09 15:37:47,686 (7f6ffe23c700) :  ERROR (model:205) - Cannot read model from /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Metadata/TV Shows/b/20eafc6bf4d82de27b8e6ba67b6f6a83520fc5e.bundle/Contents/com.plexapp.agents.subzero

**Comment by sidgaabriel** [comment]
> 
> 
> what about the below errors?
> 2018-11-09 15:28:47,291 (7f6fca7fc700) : CRITICAL (agentkit:1078) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 2.6.4.2834)', called with guid 'com.plexapp.agents.thetvdb://328724?lang=en' (most recent call last):
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
> agent.update(obj, media, lang, **kwargs)
> File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/**init**.py", line 184, in update
> all_videos = media_to_videos(media, kind=self.agent_type)
> File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/plex_media.py", line 126, in media_to_videos
> imdb_id = media.guid[len(imdb_guid_identifier):].split("?")[0]
> File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/items.py", line 35, in get_item
> item_container = Plex["library"].metadata(item_id)
> File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/interfaces/library/**init**.py", line 9, in metadata
> response = self.http.get('metadata', rating_key)
> File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/core/http.py", line 95, in get
> return self.request('GET', path, params, query, data, **kwargs)
> File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/core/http.py", line 87, in request
> response = request.request.send()
> File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/lib.py", line 33, in send
> timeout=DEFAULT_TIMEOUT)
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 194, in Request
> method=method,
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
> req = self._core.networking.http_request(url, *args, **kwargs)
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
> return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in **init**
> self.load()
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
> f = self._opener.open(req, timeout=self._timeout)
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
> response = self._open(req, data)
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
> '_open', req)
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
> result = func(*args)
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
> return self.do_open(httplib.HTTPConnection, req)
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-ecd600442/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
> raise URLError(err)
> URLError:
> 
> 2018-11-09 15:37:47,686 (7f6ffe23c700) : ERROR (model:205) - Cannot read model from /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Metadata/TV Shows/b/20eafc6bf4d82de27b8e6ba67b6f6a83520fc5e.bundle/Contents/com.plexapp.agents.subzero

I'm having the same issue since I updated Plex to 1.13.9.5456, the SZ stop downloading subtitles and my log the only issue that I could notice is the reading error above.

**Comment by pannal** [comment]
@sidgaabriel your issue is most likely unrelated. Please set SZ's logging verbosity to DEBUG (at the bottom of SZ's settings), then refresh a media file in question and attach your log zip.

**Comment by sidgaabriel** [comment]
> 
> 
> @sidgaabriel your issue is most likely unrelated. Please set SZ's logging verbosity to DEBUG (at the bottom of SZ's settings), then refresh a media file in question and attach your log zip.

Here's my log files, if there's anything else I need to do let me know.
[Logfile.zip](https://www.filedropper.com/logs18111911-31-37)
Thanks!

**Comment by pannal** [comment]
@sidgaabriel I can't see any major errors in your logs. Please follow my initial instructions and set the correct log level.

**Comment by sidgaabriel** [comment]
@pannal I didn't change anything in my system and suddenly my SZ worked again when I tried to get the log's that you wanted, thanks for you support, If I experience any other issues I'll create a thread and attach the log files as you requested. Thanks!

**Comment by pannal** [comment]
@sidgaabriel please attach them anyways, maybe I can spot something.

**Comment by sidgaabriel** [comment]
> 
> 
> @sidgaabriel please attach them anyways, maybe I can spot something.

Here's the log as you requested. 
[Log file](http://www.filedropper.com/logs18112116-49-16)

**Comment by pannal** [comment]
@sidgaabriel hmm, the only issue I see in your logs is that your PMS doesn't answer metadata requests at times. Is your server under high load?

**Comment by sidgaabriel** [comment]
> 
> 
> @sidgaabriel hmm, the only issue I see in your logs is that your PMS doesn't answer metadata requests at times. Is your server under high load?

Could be, but since I updated and restart the issue seems to be fixed. It's and old pc running Linux and PMS only, nothing else. I just connect my smart TV, open Plex app and watch my series.
